-- MySQL Script generated by MySQL Workbench
-- Wed Apr 28 01:13:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Mesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mesto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Mesto` (
  `idMesta` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(100) NULL DEFAULT NULL,
  `Opis` TEXT NULL DEFAULT NULL,
  `DnevnaKolicina` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idMesta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TipVakcine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipVakcine` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TipVakcine` (
  `idTipVakcine` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NULL DEFAULT NULL,
  `Opis` LONGTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '	',
  `VremeDoDrugeVakcinacije` INT NULL DEFAULT NULL,
  `KolicinaVakcinisanih` INT NULL DEFAULT NULL,
  `BrojNezeljenih` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idTipVakcine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ZdravstveniRadnici`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ZdravstveniRadnici` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`ZdravstveniRadnici` (
  `idZdravstveniRadnik` INT NOT NULL,
  `JMBG` VARCHAR(45) NULL DEFAULT NULL,
  `Ime` VARCHAR(45) NULL DEFAULT NULL,
  `Prezime` VARCHAR(45) NULL DEFAULT NULL,
  `Licenca` VARCHAR(45) NULL DEFAULT NULL,
  `TipRadnika` ENUM('Lekar', 'Sestra') NULL DEFAULT NULL,
  `Specijalizacija` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(512) NULL,
  PRIMARY KEY (`idZdravstveniRadnik`),
  UNIQUE INDEX `username_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Gradjanin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Gradjanin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Gradjanin` (
  `JMBG` CHAR(8) NOT NULL,
  `Ime` VARCHAR(50) NULL DEFAULT NULL,
  `Prezime` VARCHAR(50) NULL DEFAULT NULL,
  `BrojTelefona` VARCHAR(45) NULL DEFAULT NULL,
  `Adresa` VARCHAR(150) NULL DEFAULT NULL,
  `Prijava` TINYINT(1) NULL DEFAULT NULL,
  `IdTipVakcine` INT NULL DEFAULT NULL,
  `StatusPrijave` ENUM('Nije Zakazan', 'Zakazan') NULL DEFAULT NULL,
  `TerminT1` TINYINT(1) NULL DEFAULT NULL,
  `DatumT1` DATETIME NULL DEFAULT NULL,
  `StatusT1` ENUM('Uspesno', 'Neuspesno') NULL DEFAULT NULL,
  `TerminT2` TINYINT(1) NULL DEFAULT NULL,
  `DatumT2` DATETIME NULL DEFAULT NULL,
  `StatusT2` ENUM('Uspesno', 'Neuspesno') NULL DEFAULT NULL,
  `IdSestraT1` INT NULL DEFAULT NULL,
  `IdSestraT2` INT NULL DEFAULT NULL,
  `IdMesta` INT NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(512) NULL,
  PRIMARY KEY (`JMBG`),
  INDEX `fk_Gradjanin_TipVakcine_idx` (`IdTipVakcine` ASC) VISIBLE,
  INDEX `fk_Gradjanin_ZdravstveniRadnici1_idx` (`IdSestraT1` ASC) VISIBLE,
  INDEX `fk_Gradjanin_ZdravstveniRadnici2_idx` (`IdSestraT2` ASC) VISIBLE,
  INDEX `fk_Gradjanin_Mesto1_idx` (`IdMesta` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_Gradjanin_Mesto1`
    FOREIGN KEY (`IdMesta`)
    REFERENCES `mydb`.`Mesto` (`idMesta`),
  CONSTRAINT `fk_Gradjanin_TipVakcine`
    FOREIGN KEY (`IdTipVakcine`)
    REFERENCES `mydb`.`TipVakcine` (`idTipVakcine`),
  CONSTRAINT `fk_Gradjanin_ZdravstveniRadnici1`
    FOREIGN KEY (`IdSestraT1`)
    REFERENCES `mydb`.`ZdravstveniRadnici` (`idZdravstveniRadnik`),
  CONSTRAINT `fk_Gradjanin_ZdravstveniRadnici2`
    FOREIGN KEY (`IdSestraT2`)
    REFERENCES `mydb`.`ZdravstveniRadnici` (`idZdravstveniRadnik`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`IzvestajLekara`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`IzvestajLekara` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`IzvestajLekara` (
  `idIzvestaja` INT NOT NULL,
  `IdGradjanin` CHAR(8) NOT NULL,
  `Diagnoza` LONGTEXT NULL DEFAULT NULL,
  `IdTipVakcine` INT NOT NULL,
  PRIMARY KEY (`idIzvestaja`),
  INDEX `fk_IzvestajLekara_Gradjanin1_idx` (`IdGradjanin` ASC) VISIBLE,
  INDEX `fk_IzvestajLekara_TipVakcine1_idx` (`IdTipVakcine` ASC) VISIBLE,
  CONSTRAINT `fk_IzvestajLekara_Gradjanin1`
    FOREIGN KEY (`IdGradjanin`)
    REFERENCES `mydb`.`Gradjanin` (`JMBG`),
  CONSTRAINT `fk_IzvestajLekara_TipVakcine1`
    FOREIGN KEY (`IdTipVakcine`)
    REFERENCES `mydb`.`TipVakcine` (`idTipVakcine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`NezeljeneReakcije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NezeljeneReakcije` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`NezeljeneReakcije` (
  `idNezeljeneReakcije` INT NOT NULL,
  `Naziv` VARCHAR(45) NULL DEFAULT NULL,
  `Opis` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idNezeljeneReakcije`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`IzvestajLekaraImaNezeljeneReakcije`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`IzvestajLekaraImaNezeljeneReakcije` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`IzvestajLekaraImaNezeljeneReakcije` (
  `IzvestajLekara_idIzvestaja` INT NOT NULL,
  `NezeljeneReakcije_idNezeljeneReakcije` INT NOT NULL,
  PRIMARY KEY (`IzvestajLekara_idIzvestaja`, `NezeljeneReakcije_idNezeljeneReakcije`),
  INDEX `fk_IzvestajLekara_has_NezeljeneReakcije_NezeljeneReakcije1_idx` (`NezeljeneReakcije_idNezeljeneReakcije` ASC) VISIBLE,
  INDEX `fk_IzvestajLekara_has_NezeljeneReakcije_IzvestajLekara1_idx` (`IzvestajLekara_idIzvestaja` ASC) VISIBLE,
  CONSTRAINT `fk_IzvestajLekara_has_NezeljeneReakcije_IzvestajLekara1`
    FOREIGN KEY (`IzvestajLekara_idIzvestaja`)
    REFERENCES `mydb`.`IzvestajLekara` (`idIzvestaja`),
  CONSTRAINT `fk_IzvestajLekara_has_NezeljeneReakcije_NezeljeneReakcije1`
    FOREIGN KEY (`NezeljeneReakcije_idNezeljeneReakcije`)
    REFERENCES `mydb`.`NezeljeneReakcije` (`idNezeljeneReakcije`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`MestoRezervisanoPoDanu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MestoRezervisanoPoDanu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`MestoRezervisanoPoDanu` (
  `idMestoRezervisanoPoDanu` INT NOT NULL,
  `Datum` DATE NULL DEFAULT NULL,
  `BrojRezervisanih` INT NULL DEFAULT NULL,
  `IdMesta` INT NOT NULL,
  PRIMARY KEY (`idMestoRezervisanoPoDanu`),
  INDEX `fk_MestoRezervisanoPoDanu_Mesto1_idx` (`IdMesta` ASC) VISIBLE,
  CONSTRAINT `fk_MestoRezervisanoPoDanu_Mesto1`
    FOREIGN KEY (`IdMesta`)
    REFERENCES `mydb`.`Mesto` (`idMesta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`PristigleVakcine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PristigleVakcine` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`PristigleVakcine` (
  `idPristigleVakcine` INT NOT NULL,
  `RaspolozivaKolicina` INT NULL DEFAULT NULL,
  `RezervisanaKolicina` INT NULL DEFAULT NULL,
  `RokUpotrebe` DATE NULL DEFAULT NULL,
  `IdTipVakcine` INT NOT NULL,
  PRIMARY KEY (`idPristigleVakcine`),
  INDEX `fk_PristigleVakcine_TipVakcine1_idx` (`IdTipVakcine` ASC) VISIBLE,
  CONSTRAINT `fk_PristigleVakcine_TipVakcine1`
    FOREIGN KEY (`IdTipVakcine`)
    REFERENCES `mydb`.`TipVakcine` (`idTipVakcine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Admin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `idAdmin` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(512) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
