<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tipvakcine extends \App\Models\Entities\Tipvakcine implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'idtipvakcine', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'naziv', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'opis', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'vremedodrugevakcinacije', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'kolicinavakcinisanih', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'brojnezeljenih', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'izvestaji', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'pristigleKolicine'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'idtipvakcine', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'naziv', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'opis', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'vremedodrugevakcinacije', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'kolicinavakcinisanih', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'brojnezeljenih', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'izvestaji', '' . "\0" . 'App\\Models\\Entities\\Tipvakcine' . "\0" . 'pristigleKolicine'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tipvakcine $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdtipvakcine()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdtipvakcine();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipvakcine', []);

        return parent::getIdtipvakcine();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaziv($naziv = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaziv', [$naziv]);

        return parent::setNaziv($naziv);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaziv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaziv', []);

        return parent::getNaziv();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpis($opis = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpis', [$opis]);

        return parent::setOpis($opis);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpis', []);

        return parent::getOpis();
    }

    /**
     * {@inheritDoc}
     */
    public function setVremedodrugevakcinacije($vremedodrugevakcinacije = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVremedodrugevakcinacije', [$vremedodrugevakcinacije]);

        return parent::setVremedodrugevakcinacije($vremedodrugevakcinacije);
    }

    /**
     * {@inheritDoc}
     */
    public function getVremedodrugevakcinacije()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVremedodrugevakcinacije', []);

        return parent::getVremedodrugevakcinacije();
    }

    /**
     * {@inheritDoc}
     */
    public function setKolicinavakcinisanih($kolicinavakcinisanih = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKolicinavakcinisanih', [$kolicinavakcinisanih]);

        return parent::setKolicinavakcinisanih($kolicinavakcinisanih);
    }

    /**
     * {@inheritDoc}
     */
    public function getKolicinavakcinisanih()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKolicinavakcinisanih', []);

        return parent::getKolicinavakcinisanih();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrojnezeljenih($brojnezeljenih = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrojnezeljenih', [$brojnezeljenih]);

        return parent::setBrojnezeljenih($brojnezeljenih);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrojnezeljenih()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrojnezeljenih', []);

        return parent::getBrojnezeljenih();
    }

    /**
     * {@inheritDoc}
     */
    public function addIzvestaji(\App\Models\Entities\Izvestajlekara $izvestaj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIzvestaji', [$izvestaj]);

        return parent::addIzvestaji($izvestaj);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIzvestaji(\App\Models\Entities\Izvestajlekara $izvestaji)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIzvestaji', [$izvestaji]);

        return parent::removeIzvestaji($izvestaji);
    }

    /**
     * {@inheritDoc}
     */
    public function getIzvestaji()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIzvestaji', []);

        return parent::getIzvestaji();
    }

    /**
     * {@inheritDoc}
     */
    public function addPristigleKolicine(\App\Models\Entities\Pristiglevakcine $pristigleKolicine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPristigleKolicine', [$pristigleKolicine]);

        return parent::addPristigleKolicine($pristigleKolicine);
    }

    /**
     * {@inheritDoc}
     */
    public function removePristigleKolicine(\App\Models\Entities\Pristiglevakcine $pristigleKolicine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePristigleKolicine', [$pristigleKolicine]);

        return parent::removePristigleKolicine($pristigleKolicine);
    }

    /**
     * {@inheritDoc}
     */
    public function getPristigleKolicine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPristigleKolicine', []);

        return parent::getPristigleKolicine();
    }

}
