<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mesto extends \App\Models\Entities\Mesto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Mesto' . "\0" . 'idmesta', '' . "\0" . 'App\\Models\\Entities\\Mesto' . "\0" . 'naziv', '' . "\0" . 'App\\Models\\Entities\\Mesto' . "\0" . 'opis', '' . "\0" . 'App\\Models\\Entities\\Mesto' . "\0" . 'dnevnakolicina', '' . "\0" . 'App\\Models\\Entities\\Mesto' . "\0" . 'gradjanini', '' . "\0" . 'App\\Models\\Entities\\Mesto' . "\0" . 'VakcinacijaPoDanu'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Mesto' . "\0" . 'idmesta', '' . "\0" . 'App\\Models\\Entities\\Mesto' . "\0" . 'naziv', '' . "\0" . 'App\\Models\\Entities\\Mesto' . "\0" . 'opis', '' . "\0" . 'App\\Models\\Entities\\Mesto' . "\0" . 'dnevnakolicina', '' . "\0" . 'App\\Models\\Entities\\Mesto' . "\0" . 'gradjanini', '' . "\0" . 'App\\Models\\Entities\\Mesto' . "\0" . 'VakcinacijaPoDanu'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mesto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdmesta()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdmesta();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmesta', []);

        return parent::getIdmesta();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaziv($naziv = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaziv', [$naziv]);

        return parent::setNaziv($naziv);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaziv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaziv', []);

        return parent::getNaziv();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpis($opis = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpis', [$opis]);

        return parent::setOpis($opis);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpis', []);

        return parent::getOpis();
    }

    /**
     * {@inheritDoc}
     */
    public function setDnevnakolicina($dnevnakolicina = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDnevnakolicina', [$dnevnakolicina]);

        return parent::setDnevnakolicina($dnevnakolicina);
    }

    /**
     * {@inheritDoc}
     */
    public function getDnevnakolicina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDnevnakolicina', []);

        return parent::getDnevnakolicina();
    }

    /**
     * {@inheritDoc}
     */
    public function addGradjanini(\App\Models\Entities\Gradjanin $gradjanini)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGradjanini', [$gradjanini]);

        return parent::addGradjanini($gradjanini);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGradjanini(\App\Models\Entities\Gradjanin $gradjanini)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGradjanini', [$gradjanini]);

        return parent::removeGradjanini($gradjanini);
    }

    /**
     * {@inheritDoc}
     */
    public function getGradjanini()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGradjanini', []);

        return parent::getGradjanini();
    }

    /**
     * {@inheritDoc}
     */
    public function addVakcinacijaPoDanu(\App\Models\Entities\Mestorezervisanopodanu $vakcinacijaPoDanu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVakcinacijaPoDanu', [$vakcinacijaPoDanu]);

        return parent::addVakcinacijaPoDanu($vakcinacijaPoDanu);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVakcinacijaPoDanu(\App\Models\Entities\Mestorezervisanopodanu $vakcinacijaPoDanu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVakcinacijaPoDanu', [$vakcinacijaPoDanu]);

        return parent::removeVakcinacijaPoDanu($vakcinacijaPoDanu);
    }

    /**
     * {@inheritDoc}
     */
    public function getVakcinacijaPoDanu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVakcinacijaPoDanu', []);

        return parent::getVakcinacijaPoDanu();
    }

}
