<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Gradjanin extends \App\Models\Entities\Gradjanin implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'jmbg', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'ime', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'prezime', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'brojtelefona', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'adresa', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'prijava', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'statusprijave', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'termint1', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'datumt1', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'statust1', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'termint2', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'datumt2', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'statust2', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'email', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'password', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'idmesta', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'idtipvakcine', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'idsestrat1', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'idsestrat2', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'izvestaji'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'jmbg', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'ime', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'prezime', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'brojtelefona', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'adresa', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'prijava', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'statusprijave', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'termint1', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'datumt1', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'statust1', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'termint2', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'datumt2', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'statust2', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'email', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'password', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'idmesta', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'idtipvakcine', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'idsestrat1', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'idsestrat2', '' . "\0" . 'App\\Models\\Entities\\Gradjanin' . "\0" . 'izvestaji'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Gradjanin $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getJmbg()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getJmbg();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJmbg', []);

        return parent::getJmbg();
    }

    /**
     * {@inheritDoc}
     */
    public function setIme($ime = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIme', [$ime]);

        return parent::setIme($ime);
    }

    /**
     * {@inheritDoc}
     */
    public function getIme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIme', []);

        return parent::getIme();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrezime($prezime = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrezime', [$prezime]);

        return parent::setPrezime($prezime);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrezime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrezime', []);

        return parent::getPrezime();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrojtelefona($brojtelefona = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrojtelefona', [$brojtelefona]);

        return parent::setBrojtelefona($brojtelefona);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrojtelefona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrojtelefona', []);

        return parent::getBrojtelefona();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresa($adresa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresa', [$adresa]);

        return parent::setAdresa($adresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresa', []);

        return parent::getAdresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrijava($prijava = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrijava', [$prijava]);

        return parent::setPrijava($prijava);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrijava()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrijava', []);

        return parent::getPrijava();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatusprijave($statusprijave = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatusprijave', [$statusprijave]);

        return parent::setStatusprijave($statusprijave);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusprijave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusprijave', []);

        return parent::getStatusprijave();
    }

    /**
     * {@inheritDoc}
     */
    public function setTermint1($termint1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTermint1', [$termint1]);

        return parent::setTermint1($termint1);
    }

    /**
     * {@inheritDoc}
     */
    public function getTermint1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTermint1', []);

        return parent::getTermint1();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatumt1($datumt1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatumt1', [$datumt1]);

        return parent::setDatumt1($datumt1);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatumt1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatumt1', []);

        return parent::getDatumt1();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatust1($statust1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatust1', [$statust1]);

        return parent::setStatust1($statust1);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatust1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatust1', []);

        return parent::getStatust1();
    }

    /**
     * {@inheritDoc}
     */
    public function setTermint2($termint2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTermint2', [$termint2]);

        return parent::setTermint2($termint2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTermint2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTermint2', []);

        return parent::getTermint2();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatumt2($datumt2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatumt2', [$datumt2]);

        return parent::setDatumt2($datumt2);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatumt2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatumt2', []);

        return parent::getDatumt2();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatust2($statust2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatust2', [$statust2]);

        return parent::setStatust2($statust2);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatust2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatust2', []);

        return parent::getStatust2();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmesta(\App\Models\Entities\Mesto $idmesta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmesta', [$idmesta]);

        return parent::setIdmesta($idmesta);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmesta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmesta', []);

        return parent::getIdmesta();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipvakcine(\App\Models\Entities\Tipvakcine $idtipvakcine = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipvakcine', [$idtipvakcine]);

        return parent::setIdtipvakcine($idtipvakcine);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipvakcine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipvakcine', []);

        return parent::getIdtipvakcine();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsestrat1(\App\Models\Entities\Zdravstveniradnici $idsestrat1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsestrat1', [$idsestrat1]);

        return parent::setIdsestrat1($idsestrat1);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsestrat1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsestrat1', []);

        return parent::getIdsestrat1();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdsestrat2(\App\Models\Entities\Zdravstveniradnici $idsestrat2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdsestrat2', [$idsestrat2]);

        return parent::setIdsestrat2($idsestrat2);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdsestrat2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsestrat2', []);

        return parent::getIdsestrat2();
    }

    /**
     * {@inheritDoc}
     */
    public function addIzvestaji(\App\Models\Entities\Izvestajlekara $izvestaji)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIzvestaji', [$izvestaji]);

        return parent::addIzvestaji($izvestaji);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIzvestaji(\App\Models\Entities\Izvestajlekara $izvestaji)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIzvestaji', [$izvestaji]);

        return parent::removeIzvestaji($izvestaji);
    }

    /**
     * {@inheritDoc}
     */
    public function getIzvestaji()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIzvestaji', []);

        return parent::getIzvestaji();
    }

}
