<?php

namespace App\Models\Proxies\__CG__\App\Models\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pristiglevakcine extends \App\Models\Entities\Pristiglevakcine implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Pristiglevakcine' . "\0" . 'idpristiglevakcine', '' . "\0" . 'App\\Models\\Entities\\Pristiglevakcine' . "\0" . 'raspolozivakolicina', '' . "\0" . 'App\\Models\\Entities\\Pristiglevakcine' . "\0" . 'rezervisanakolicina', '' . "\0" . 'App\\Models\\Entities\\Pristiglevakcine' . "\0" . 'rokupotrebe', '' . "\0" . 'App\\Models\\Entities\\Pristiglevakcine' . "\0" . 'idtipvakcine'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entities\\Pristiglevakcine' . "\0" . 'idpristiglevakcine', '' . "\0" . 'App\\Models\\Entities\\Pristiglevakcine' . "\0" . 'raspolozivakolicina', '' . "\0" . 'App\\Models\\Entities\\Pristiglevakcine' . "\0" . 'rezervisanakolicina', '' . "\0" . 'App\\Models\\Entities\\Pristiglevakcine' . "\0" . 'rokupotrebe', '' . "\0" . 'App\\Models\\Entities\\Pristiglevakcine' . "\0" . 'idtipvakcine'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pristiglevakcine $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdpristiglevakcine()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdpristiglevakcine();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpristiglevakcine', []);

        return parent::getIdpristiglevakcine();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaspolozivakolicina($raspolozivakolicina = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaspolozivakolicina', [$raspolozivakolicina]);

        return parent::setRaspolozivakolicina($raspolozivakolicina);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaspolozivakolicina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaspolozivakolicina', []);

        return parent::getRaspolozivakolicina();
    }

    /**
     * {@inheritDoc}
     */
    public function setRezervisanakolicina($rezervisanakolicina = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRezervisanakolicina', [$rezervisanakolicina]);

        return parent::setRezervisanakolicina($rezervisanakolicina);
    }

    /**
     * {@inheritDoc}
     */
    public function getRezervisanakolicina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRezervisanakolicina', []);

        return parent::getRezervisanakolicina();
    }

    /**
     * {@inheritDoc}
     */
    public function setRokupotrebe($rokupotrebe = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRokupotrebe', [$rokupotrebe]);

        return parent::setRokupotrebe($rokupotrebe);
    }

    /**
     * {@inheritDoc}
     */
    public function getRokupotrebe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRokupotrebe', []);

        return parent::getRokupotrebe();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdtipvakcine(\App\Models\Entities\Tipvakcine $idtipvakcine = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdtipvakcine', [$idtipvakcine]);

        return parent::setIdtipvakcine($idtipvakcine);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdtipvakcine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdtipvakcine', []);

        return parent::getIdtipvakcine();
    }

}
